Changed the name of Media embed button to be Media Library
Vardot/varbase pull request #12
Opened 2017-05-16 15:25 UTC by yasmeensalah

please revies

2017-05-16 15:26 UTC, moerazem commented on modules/varbase_features/varbase_media/varbase_media.install
> +	// Change name of Media embed button to be “Media Library".
@yasmeensalah please change your editor's settings to use double spaces for tabs. No tabs allowed in Drupal coding standards :)

2017-05-17 07:04 UTC, Natshah requested changes

2017-05-17 07:04 UTC, Natshah commented on modules/varbase_features/varbase_media/varbase_media.install
> +  $embed_button_config->get('label')=='media' ? $embed_button_config->set('label','Media Library')
- Not sure why the **shorthand!** condition at this point.
- A normal **If** statement will do with the Drupal 8 standard.
- A smarter condition could include the call for the **strtolower** php function to lower the old label then compare.

2017-05-17 09:48 UTC, Natshah commented on modules/varbase_features/varbase_media/varbase_media.install
> +  {
Drupal Standard coding. keep the { in the same line with the if statement

2017-05-17 09:50 UTC, Natshah commented on modules/varbase_features/varbase_media/varbase_media.install
> +  {
Please, keep the { in the same line with the If statement

2017-05-17 17:01 UTC, Natshah commented
Committed to the Drupal.org first. No need to marge

2017-05-17 17:01 UTC, closed without merging